add PRDC
takuseno/d3rlpy pull request #431
Opened 2024-11-07 05:54 UTC by liyc-ai

Add Implementation of PRDC, arXiv link: https://arxiv.org/abs/2306.06569

2024-11-07 13:01 UTC, takuseno requested changes
Thank you for your PR! This looked like a nice addition to d3rlpy :smile: I found a dependency problem as I commented. Please take a look at that. There might be trivial code changes that I would add. But, that's my job after we merge this PR. Thanks again!

2024-11-08 02:11 UTC, liyc-ai commented on setup.py
> +            "scipy",
Thanks to your careful review. I have made the corresponding changes.

2024-11-08 04:55 UTC, liyc-ai commented on setup.py
> +            "scipy",
btw, I've also fix errors from `./scripts/lint`.

2024-11-08 08:52 UTC, takuseno approved these changes
LGTM. Thank you for the update!

2024-11-08 08:52 UTC, merged